language: rust
rust:
  - nightly
git:
  submodules: false
script:
  - ./gendoc.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: travis-test
  local-dir: doc
